version: "3"

services:
  app:
    image: node
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: npm start
    ports:
      - 3000:3000

volumes:
  node_modules:
